version: '3.8'
services:
  app:
    build: ..
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/yourdb
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=yourdb
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: